### ISSUE TITLE
Add logging aspect to iffy_get_data.sh 

### ISSUE THREAD

**Issue by mr-devs** [mr-devs/top-FIBers#22]
This script will need to be updated to log its progress and any errors.

**Comment by nick-c-liu** [comment]
logs now go to `logs/iffy_getdata.out`

**Comment by mr-devs** [comment]
I don't think we are really logging any information in this script at the moment. This isn't urgent, but I don't want to forget about it so let's leave this open for now.

**Comment by mr-devs** [comment]
See #28 which includes this functionality.
