### ISSUE TITLE
Add line for profile_links.py

### ISSUE THREAD

**Issue by mr-devs** [mr-devs/top-FIBers#31]
https://github.com/mr-devs/top-FIBers/blob/5eacd166e5e859093aa70ad2abcb5bbfd97f0691/data-loader/database_functions/README.md?plain=1#L8

Just noticed that the `Contents` section of this README does not include a line item for the `profile_links.py` file. Can you please add one? Thanks!

**Comment by pasan04** [comment]
Add the documentation. -> https://github.com/mr-devs/top-FIBers/pull/32
