### ISSUE TITLE
Clickable account icons

### ISSUE THREAD

**Issue by mr-devs** [mr-devs/top-FIBers#43]
On the "Accounts" page, it looks like we can no longer click the user icon to visit an account's twitter/facebook page. I think that Fil had asked you to make the text no longer look like a hyperlink when we added the "Unfollow" button but I would still like to be able to click the icon to visit. So we would be able to visit both ways, via the unfollow button but also the icon. Can you please add that functionality back in when you get a chance?

Thanks!

**Comment by pasan04** [comment]
Sorry for my misunderstanding in there. I corrected it!

**Comment by mr-devs** [comment]
Looks great. thank you!
