### ISSUE TITLE
Update FAQ

### ISSUE THREAD

**Issue by mr-devs** [mr-devs/top-FIBers#47]
Hi Pasan, can you please update the FAQ sections outlined below with the following text? These have changed since we've changed the list of domains slightly.

Thanks!

---

### How do you define misinformation?

We adopt a common definition of misinformation utilized in academic research, which focuses on a source of information “that mimics news media content in form but not in organizational process or intent”[ (Lazer et al, Science, 2018)](https://www.science.org/doi/10.1126/science.aao2998). With this definition, we search for posts that contain at least one link to sources within a list that is curated by an independent third party, [Iffy.news](https://iffy.news/). Specifically, we include sources that have been marked by [Media Bias Fact Check](https://mediabiasfactcheck.com/) (MBFC) as having a "low" or "very-low" "MBFC Factual" score.

According to [MBFC methodology](https://mediabiasfactcheck.com/methodology/), a source in these categories "rarely uses credible sources and is not trustworthy for reliable information" and "need[s] to be fact-checked for intentional fake news, conspiracy, and propaganda." Since a source's MBFC Factual score can change, we update our list of sources each month prior to releasing a new Top FIBers monthly report. These updates do not affect prior reports.

#### Facebook

Facebook data are gathered using the [CrowdTangle API ](https://github.com/CrowdTangle/API). Specifically, we utilize the [/posts/search/](https://github.com/CrowdTangle/API/wiki/Search) endpoint. As a result of utilizing CrowdTangle, we are limited to collecting public posts (see the [CrowdTangle documentation ](https://help.crowdtangle.com/en/articles/4201940-about-us)for more details).

Data for all months in 2022 as well as January--March of 2023 were gathered during the week of April 24, 2023. After that point, Facebook data are collected within the first week of the following month (depending on how long it takes for all data to download). For example, April 2023 data were collected during the first week of March 2023. We collect public posts linking to at least one of the low-credibility sources (see **How do you define misinformation?** for more details). `please link the bold portion to the section above`.

#### Twitter
Twitter data are collected with the enterprise-level [Decahose endpoint](https://github.com/CrowdTangle/API). The Decahose delivers a 10% random sample of all tweets in real time. From this, we then collect all tweets that link to at least one of the credibility sources.

As Twitter's recent API changes have made continuing this data collection [virtually impossible](https://www.wired.com/story/twitter-data-api-prices-out-nearly-everyone/), we will no longer be able to continue analyzing Twitter's biggest superspreaders of misinformation.

**Comment by pasan04** [comment]
Added the content to About Page. Thanks!

**Comment by mr-devs** [comment]
Looks great. Thanks! If you can remember to bring this up on Thursday, I would appreciate it. Fil will want to review the text but I may forget.
